MVCWEB/MVCWEB/Models/Categoria.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.Guantes = new HashSet<Guantes>();
        }
    
        public int id { get; set; }
        public string NombreCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guantes> Guantes { get; set; }
    }
}

MVCWEB/MVCWEB/Controllers/CategoriaController.cs
using MVCWEB.Models;
using MVCWEB.Models.CategoriaModel;
using MVCWEB.Models.MarcaModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWEB.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {
            List<categoriaModel> lst = null;
            using (TiendaOnlineEntities1 db=new TiendaOnlineEntities1())
            {
                lst = (from d in db.Categoria
                       select new categoriaModel
                       {
                           idCategoria=d.id,
                           NombreCategoria=d.NombreCategoria
                       }

                    ).ToList();
            }
            return View(lst);
        }

        // GET: Categoria/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Categoria/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categoria/Create
        [HttpPost]
        public ActionResult Create(categoriaRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            try
            {
                using (var db = new TiendaOnlineEntities1())
                {
                    Categoria cat = new Categoria();
                    cat.NombreCategoria = request.NombreCategoria;
                    db.Categoria.Add(cat);
                    db.SaveChanges();
                }

            }
            catch (Exception)
            {

                throw;
            }

              return Redirect(Url.Content("~/Categoria/"));
        }

        // GET: Categoria/Edit/5
        public ActionResult Edit(int id)
        {
            editCategoria cat = new editCategoria();
            using (var db=new TiendaOnlineEntities1())
            {
                var Cat1 = db.Categoria.Find(id);
                cat.NombreCategoria = Cat1.NombreCategoria;
                cat.idCategoria = Cat1.id;
            }
            return View(cat);
        }

        // POST: Categoria/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, editCategoria request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }
            using (var db=new TiendaOnlineEntities1())
            {
                var Cat = db.Categoria.Find(request.idCategoria);
                Cat.NombreCategoria = request.NombreCategoria;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Categoria/"));
        }

        // GET: Categoria/Delete/5
        public ActionResult Delete(int id)
        {
            using (TiendaOnlineEntities1 db=new TiendaOnlineEntities1())
            {
                var Cat1 = db.Categoria.Find(id);
                db.Categoria.Remove(Cat1);
                db.SaveChanges();
            }
            return Redirect("~/Categoria/");
        }

        // POST: Categoria/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCWEB/MVCWEB/Views/Categoria/Create.cshtml
@model MVCWEB.Models.CategoriaModel.categoriaRequest
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "Categoria", FormMethod.Post, new { role = "form", @class = "form formulario" }))
{
    @Html.AntiForgeryToken()

    <h2>Registro de Marca</h2>
    <hr />

    <div class="form-group grupoControl">
        @Html.ValidationMessage("error", new { @class = "text-danger" })
        @Html.LabelFor(d => d.NombreCategoria)
        @Html.TextBoxFor(d => d.NombreCategoria, new { @class = "form-control form-control-lg" })

    </div>

    <div class="grupoControl">
        <hr />
        <button style="width:280px; height:100px;padding:0em" type="submit">Guardar</button>
        <hr />
    </div>
}

MVCWEB/MVCWEB/Views/Categoria/Edit.cshtml
@model MVCWEB.Models.CategoriaModel.editCategoria
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Edit", "Categoria", FormMethod.Post, new { role = "form", @class = "formulario" }))
            {
                <h2>Edición de Categoria</h2>
                <hr />
                @Html.HiddenFor(d => d.idCategoria)
                @Html.AntiForgeryToken()

                <div class="form-group grupoControl">

                    @Html.ValidationMessage("error", new { @class = "text-danger" })
                    @Html.LabelFor(d => d.NombreCategoria)
                    @Html.TextBoxFor(d => d.NombreCategoria, new { @class = "form-control" })

                </div>


                <div class="form-group grupoControl">
                    <hr />
                    <button style="width:280px; height:100px;padding:0em" type="submit">Actualizar</button>
                    <hr />
                </div>
            }
        </div>
    </div>

MVCWEB/MVCWEB/Views/Categoria/Index.cshtml
@model List<MVCWEB.Models.CategoriaModel.categoriaModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="row">
    <div class="col-md-12">
        <hr />
        <button style="height:80px;padding:0em;" type="submit" onclick="document.location.href='@Url.Content("~/Categoria/Create/")'" name="name" value="Nuevo">Nuevo</button>
        <hr />
    </div>
</div>

<hr />


<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped table-hover table-responsive-md">
            <thead class="thead-dark">
                <tr>
                    <th style="font-family:cursive;text-align:center">#</th>
                    <th style="font-family:cursive;text-align:center">Nombre Categoria</th>
                    <th style="font-family:cursive;text-align:center">Acciones</th>
                </tr>
            </thead>
            @foreach (var Cat in Model)
            {
                <tr>

                    <td style="font-family:cursive;text-align:center">@Cat.idCategoria</td>
                    <td style="font-family:cursive;text-align:center">@Cat.NombreCategoria</td>
                    <td style="font-family:cursive;text-align:center">
                        <button type="button" style="padding:0em" onclick="document.location.href='@Url.Content("~/Categoria/Edit/"+Cat.idCategoria)'" id="buttonRed" name="name" value="Actualizar">Actualizar</button>

                        <button type="button" style="padding:0em" onclick="document.location.href='@Url.Content("~/Categoria/Delete/"+Cat.idCategoria)'" id="buttonYellow" name="name" value="Eliminar">Eliminar</button>
                    </td>
                </tr>

            }

        </table>
    </div>
</div>