MVCWEB/MVCWEB/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Guantes = new HashSet<Guantes>();
        }
    
        public int id { get; set; }
        public string NombreMarca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guantes> Guantes { get; set; }
    }
}

MVCWEB/MVCWEB/Controllers/MarcaController.cs
using MVCWEB.Models;
using MVCWEB.Models.MarcaModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWEB.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            List<marcaModel> lst = null;
            using (TiendaOnlineEntities1 db = new TiendaOnlineEntities1())
            {
                lst=(from d in db.Marca
                     select new marcaModel {
                         idMarca=d.id,
                         NombreMarca=d.NombreMarca
                     }).ToList();
            }
            return View(lst);
        }

        // GET: Marca/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Marca/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        [HttpPost]
        public ActionResult Create(CategoriaRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            using (var db=new TiendaOnlineEntities1())
            {
                Marca Marca1 = new Marca();
                Marca1.NombreMarca = request.NombreMarca;
                db.Marca.Add(Marca1);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Marca/"));
        }

        // GET: Marca/Edit/5
        public ActionResult Edit(int id)
        {
            EditMarca Marca = new EditMarca();
            using (var db=new TiendaOnlineEntities1())
            {
                var Marca1 = db.Marca.Find(id);
                Marca.NombreMarca = Marca1.NombreMarca;
                Marca.idMarca = Marca1.id;
            }
            return View(Marca);
        }

        // POST: Marca/Edit/5
        [HttpPost]
        public ActionResult Edit(EditMarca request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            using (var db=new TiendaOnlineEntities1())
            {
                var Marca1 = db.Marca.Find(request.idMarca);
                Marca1.NombreMarca = request.NombreMarca;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Marca/"));
        }

        // GET: Marca/Delete/5
        public ActionResult Delete(int id)
        {
            using (TiendaOnlineEntities1 db=new TiendaOnlineEntities1())
            {
                var Marca1 = db.Marca.Find(id);
                db.Marca.Remove(Marca1);
                db.SaveChanges();
            }
            return Redirect("~/Marca/");
        }

        // POST: Marca/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCWEB/MVCWEB/Views/Marca/Create.cshtml
@model MVCWEB.Models.MarcaModel.CategoriaRequest
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "Marca", FormMethod.Post, new { role = "form", @class = "form formulario" }))
{
    @Html.AntiForgeryToken()

    <h2>Registro de Marca</h2>
    <hr />

    <div class="form-group grupoControl">
        @Html.ValidationMessage("error", new { @class = "text-danger" })
        @Html.LabelFor(d => d.NombreMarca)
        @Html.TextBoxFor(d => d.NombreMarca, new { @class = "form-control form-control-lg" })

    </div>

    <div class="grupoControl">
        <hr />
        <button style="width:280px; height:100px;padding:0em" type="submit">Guardar</button>
        <hr />
    </div>
}

MVCWEB/MVCWEB/Views/Marca/Edit.cshtml
@model MVCWEB.Models.MarcaModel.EditMarca
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Edit", "Marca", FormMethod.Post, new { role = "form", @class = "formulario" }))
        {
            <h2>Edición de Marca</h2>
            <hr />
            @Html.HiddenFor(d => d.idMarca)
            @Html.AntiForgeryToken()

            <div class="form-group grupoControl">

                @Html.ValidationMessage("error", new { @class = "text-danger" })
                @Html.LabelFor(d => d.NombreMarca)
                @Html.TextBoxFor(d => d.NombreMarca, new { @class = "form-control" })

            </div>


            <div class="form-group grupoControl">
                <hr />
                <button style="width:280px; height:100px;padding:0em" type="submit">Actualizar</button>
                <hr />
            </div>
        }
    </div>
</div>

MVCWEB/MVCWEB/Views/Marca/Index.cshtml
@model List<MVCWEB.Models.MarcaModel.marcaModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="row">
    <div class="col-md-12">
        <hr />
        <button style="height:80px;padding:0em;" type="submit" onclick="document.location.href='@Url.Content("~/Marca/Create/")'" name="name" value="Nuevo">Nuevo</button>
        <hr />
    </div>
</div>

<hr />


<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped table-hover table-responsive-md">
            <thead class="thead-dark">
                <tr>
                    <th style="font-family:cursive;text-align:center">#</th>
                    <th style="font-family:cursive;text-align:center">Marca</th>
                    <th style="font-family:cursive;text-align:center">Acciones</th>
                </tr>
            </thead>
            @foreach (var Marca in Model)
            {
                <tr>

                    <td style="font-family:cursive;text-align:center">@Marca.idMarca</td>
                    <td style="font-family:cursive;text-align:center">@Marca.NombreMarca</td>
                    <td style="font-family:cursive;text-align:center">
                        <button type="button" style="padding:0em" onclick="document.location.href='@Url.Content("~/Marca/Edit/"+Marca.idMarca)'" id="buttonRed" name="name" value="Actualizar">Actualizar</button>

                        <button type="button" style="padding:0em" onclick="document.location.href='@Url.Content("~/Marca/Delete/"+Marca.idMarca)'" id="buttonYellow" name="name" value="Eliminar">Eliminar</button>
                    </td>
                </tr>

            }

        </table>
    </div>
</div>