MVCWEB/MVCWEB/Models/Modelo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modelo()
        {
            this.Guantes = new HashSet<Guantes>();
        }
    
        public int id { get; set; }
        public string NombreModelo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guantes> Guantes { get; set; }
    }
}

MVCWEB/MVCWEB/Controllers/ModeloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCWEB.Models;
using MVCWEB.Models.ModeloModel;
using MVCWEB.Models.ModeloRequest;

namespace MVCWEB.Controllers
{
    public class ModeloController : Controller
    {
        // GET: Modelo
        public ActionResult Index()
        {
            List<modeloModel> lst = null;
            using (TiendaOnlineEntities1 db=new TiendaOnlineEntities1())
            {
                lst = (from d in db.Modelo
                       select new modeloModel
                       {
                           idModelo = d.id,
                           NombreModelo = d.NombreModelo
                       }).ToList();
            }

            return View(lst);
        }

        // GET: Modelo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Modelo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Modelo/Create
        [HttpPost]
        public ActionResult Create(modeloRequest Request)
        {
            if (!ModelState.IsValid)
            {
                return View(Request);
            }
            using (var db = new TiendaOnlineEntities1())
            {
                Modelo Modelo = new Modelo();
                Modelo.NombreModelo = Request.NombreModelo;
                db.Modelo.Add(Modelo);
                db.SaveChanges();

            }
            return Redirect(Url.Content("~/Modelo/"));
        }

        // GET: Modelo/Edit/5
        public ActionResult Edit(int id)
        {
            modeloRequestEdit modelo = new modeloRequestEdit();
            using (var db=new TiendaOnlineEntities1())
            {
                var Modelo1 = db.Modelo.Find(id);
                modelo.NombreModelo = Modelo1.NombreModelo;
                modelo.idModelo = Modelo1.id;
            }
            return View(modelo);
        }

        // POST: Modelo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, modeloRequestEdit request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            using (var db = new TiendaOnlineEntities1())
            {
                var Modelo1 = db.Modelo.Find(request.idModelo);
                Modelo1.NombreModelo = request.NombreModelo;
                db.SaveChanges();
            }
                return Redirect(Url.Content("~/Modelo/"));
        }

        // GET: Modelo/Delete/5
        public ActionResult Delete(int id)
        {
            using (TiendaOnlineEntities1 db=new TiendaOnlineEntities1())
            {
                var Modelo1 = db.Modelo.Find(id);
                db.Modelo.Remove(Modelo1);
                db.SaveChanges();
            }
            return Redirect("~/Modelo/");
        }

        // POST: Modelo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVCWEB/MVCWEB/Views/Modelo/Create.cshtml
@model MVCWEB.Models.ModeloRequest.modeloRequest
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "Modelo", FormMethod.Post, new { role = "form", @class = "form formulario" }))
{
    @Html.AntiForgeryToken()

    <h2>Registro de Usuarios</h2>
    <hr />

    <div class="form-group grupoControl">
        @Html.ValidationMessage("error", new { @class = "text-danger" })
        @Html.LabelFor(d => d.NombreModelo)
        @Html.TextBoxFor(d => d.NombreModelo, new { @class = "form-control form-control-lg" })

    </div>

    <div class="grupoControl">
        <hr />
        <button style="width:280px; height:100px;padding:0em" type="submit">Guardar</button>
        <hr />
    </div>
}

MVCWEB/MVCWEB/Views/Modelo/Edit.cshtml
@model MVCWEB.Models.ModeloRequest.modeloRequestEdit
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Edit", "Modelo", FormMethod.Post, new { role = "form", @class = "formulario" }))
        {
            @Html.HiddenFor(d => d.idModelo)
            @Html.AntiForgeryToken()

            <div class="form-group grupoControl">

                @Html.ValidationMessage("error", new { @class = "text-danger" })
                @Html.LabelFor(d => d.NombreModelo)
                @Html.TextBoxFor(d => d.NombreModelo, new { @class = "form-control" })

            </div>
            

            <div class="form-group grupoControl">
                <hr />
                <input type="submit" name="name" value="Guardar" class="btn btn-success" />
                <hr />
            </div>
        }
    </div>
</div>

MVCWEB/MVCWEB/Views/Modelo/Index.cshtml
@model  List<MVCWEB.Models.ModeloModel.modeloModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="row">
    <div class="col-md-12">
        <hr />
        <button style="height:80px;padding:0em;" type="submit" onclick="document.location.href='@Url.Content("~/Modelo/Create/")'" name="name" value="Nuevo">Nuevo</button>
        <hr />
    </div>
</div>

<hr />


<div class="row">
    <div class="col-lg-12">
        <table class="table table-striped table-hover table-responsive-xl">
            <thead class="thead-dark">
                <tr>
                    <th style="font-family:cursive;text-align:center">#</th>
                    <th style="font-family:cursive;text-align:center">Modelo</th>
                    <th style="font-family:cursive;text-align:center">Acciones</th>

                </tr>
            </thead>
            @foreach (var modelo in Model)
            {
                <tr>

                    <td style="font-family:cursive;text-align:center">@modelo.idModelo</td>
                    <td style="font-family:cursive;text-align:center">@modelo.NombreModelo</td>
                    
                    <td style="font-family:cursive;text-align:center">
                        <button type="button" style="padding:0em" onclick="document.location.href='@Url.Content("~/Modelo/Edit/"+modelo.idModelo)'" id="buttonRed" name="name" value="Actualizar">Actualizar</button>
                        <button type="button" style="padding:0em" onclick="document.location.href='@Url.Content("~/Modelo/Delete/"+modelo.idModelo)'" id="buttonYellow" name="name" value="Eliminar">Eliminar</button>
                    </td>
                </tr>

            }

        </table>
    </div>
</div>